/*
|--------------------------------------------------------------------------
| Routes file
|--------------------------------------------------------------------------
| Auto-generated by Girouette - DO NOT EDIT
|
| The routes file is used for defining the HTTP routes.
|
*/
