import 'reflect-metadata'
import type { ApplicationService, LoggerService } from '@adonisjs/core/types'
import { join } from 'node:path'
import { readdir, writeFile, mkdir, readFile } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'
import { createHash } from 'node:crypto'
import { hmrRouteDetector } from '../src/hmr_detector.js'
import { MiddlewareFn, ParsedNamedMiddleware, ResourceActionNames } from '@adonisjs/core/types/http'
import {
  REFLECT_RESOURCE_MIDDLEWARE_KEY,
  REFLECT_RESOURCE_NAME_KEY,
  REFLECT_ROUTES_KEY,
  REFLECT_GROUP_KEY,
  REFLECT_GROUP_MIDDLEWARE_KEY,
  REFLECT_GROUP_DOMAIN_KEY,
  REFLECT_RESOURCE_ONLY_KEY,
  REFLECT_RESOURCE_EXCEPT_KEY,
  REFLECT_RESOURCE_API_ONLY_KEY,
  REFLECT_RESOURCE_PARAMS_KEY,
} from '../src/constants.js'
import {
  ControllerToProcess,
  GirouetteConfig,
  GirouetteRoute,
  GroupMetadata,
  MiddlewareConfig,
  OneOrMore,
} from '../src/types.js'
import { cwd } from 'node:process'

/**
 * The GirouetteProvider is responsible for generating a routes.ts file from decorated controllers.
 * It scans the application's controllers directory and generates a standard AdonisJS routes file.
 */
export default class GirouetteProvider {
  #logger: LoggerService | null = null
  #controllersPath: string = join(cwd(), 'app')
  #config: GirouetteConfig | null = null
  #routeLines: string[] = []

  constructor(protected app: ApplicationService) {}

  set controllersPath(path: string) {
    this.#controllersPath = path
  }

  async boot() {
    // Provider is booted
  }

  /**
   * Check if a controller's routes changed (for HMR detection)
   * Returns true if routes changed and full reload is needed
   */
  async checkControllerRoutesChanged(controllerPath: string): Promise<boolean> {
    try {
      const path = pathToFileURL(controllerPath)
      const controller = await import(`${path.href}?t=${Date.now()}`)

      if (!controller.default) {
        return false
      }

      return hmrRouteDetector.didRoutesChange(controllerPath, controller.default)
    } catch (error) {
      this.#logger?.error({ error, controllerPath }, '[Girouette] Error checking controller routes')
      return false
    }
  }

  /**
   * Starts the provider by scanning controllers and generating routes.ts
   */
  async start() {
    if (!this.#logger) {
      this.#logger = await this.app.container.make('logger')
    }
    if (!this.#config) {
      this.#config = this.app.config.get('girouette')
    }

    // Clear previous routes (important for dev server restarts)
    this.#routeLines = []
    this.#logger?.debug('[Girouette] Cleared previous routes')

    // Step 1: Scan controllers and collect route definitions
    await this.#scanControllersDirectory(this.#controllersPath)
    this.#logger?.info(
      `[Girouette] Scanned controllers, collected ${this.#routeLines.length} routes`
    )

    // Step 2: Generate start/routes.ts file
    await this.#generateRoutesFile()
  }

  /**
   * Generates a standard start/routes.ts file (only if routes changed)
   */
  async #generateRoutesFile() {
    const startDir = join(this.app.appRoot.pathname, 'start')
    const routesFilePath = join(startDir, 'routes.ts')
    const cacheFilePath = join(startDir, '.girouette-cache')

    // Create start directory if it doesn't exist
    await mkdir(startDir, { recursive: true })

    // Generate route content (just the routes, not the full file)
    const routeContent = this.#routeLines.join('\n')
    this.#logger?.debug(`[Girouette] Generated ${this.#routeLines.length} route lines`)

    // Calculate hash of route definitions
    const currentHash = createHash('sha256').update(routeContent).digest('hex')
    this.#logger?.info(`[Girouette] Current routes hash: ${currentHash.substring(0, 8)}...`)

    // Check if routes have changed by comparing with cached hash
    let previousHash: string | null = null
    try {
      const cachedContent = await readFile(cacheFilePath, 'utf-8')
      previousHash = cachedContent.trim()
      this.#logger?.info(`[Girouette] Previous routes hash: ${previousHash.substring(0, 8)}...`)
    } catch (error) {
      this.#logger?.info('[Girouette] No cache file found, will create new one')
    }

    // Only write if routes changed
    if (currentHash === previousHash) {
      this.#logger?.info('[Girouette] ✓ Routes unchanged, skipping file write (HMR preserved)')
      return
    }

    this.#logger?.info('[Girouette] ✗ Routes changed, regenerating start/routes.ts')

    // Generate the full routes file content
    const fileContent = `/*
|--------------------------------------------------------------------------
| Routes file
|--------------------------------------------------------------------------
| Auto-generated by Girouette - DO NOT EDIT
|
| The routes file is used for defining the HTTP routes.
|
*/

import router from '@adonisjs/core/services/router'
import { middleware } from '#start/kernel'
import { controllers } from '#generated/controllers'

${routeContent}
`

    // Write the file and cache
    this.#logger?.debug(`[Girouette] Writing cache to: ${cacheFilePath}`)
    await Promise.all([
      writeFile(routesFilePath, fileContent, 'utf-8'),
      writeFile(cacheFilePath, currentHash, 'utf-8'),
    ])

    this.#logger?.info('[Girouette] Routes changed, regenerated start/routes.ts')
  }

  /**
   * Recursively scans the directory for controller files
   */
  async #scanControllersDirectory(directory: string) {
    const files = await readdir(directory, { withFileTypes: true })

    for (const file of files) {
      const fullPath = join(directory, file.name)

      if (file.isDirectory()) {
        await this.#scanControllersDirectory(fullPath)
        continue
      }

      if (this.#isControllerFile(file.name)) {
        await this.#processControllerFile(fullPath)
      }
    }
  }

  /**
   * Checks if a file is a controller file based on its name
   */
  #isControllerFile(fileName: string) {
    if (!this.#config?.controllersGlob) {
      return fileName.endsWith('_controller.ts') || fileName.endsWith('_controller.js')
    }
    return this.#config?.controllersGlob.test(fileName)
  }

  /**
   * Processes a controller file by importing it and collecting routes
   */
  async #processControllerFile(filePath: string) {
    try {
      const path = pathToFileURL(filePath)
      const controllerToProcess: ControllerToProcess = {
        controller: await import(path.href),
        importUrl: path,
      }

      this.#collectControllerRoutes(controllerToProcess)
      this.#collectResourceRoutes(controllerToProcess)
    } catch (error) {
      this.#logger?.error({ error, filePath }, '[Girouette] Error processing controller file')
    }
  }

  /**
   * Collects all decorated routes from a controller
   */
  #collectControllerRoutes(controller: ControllerToProcess) {
    const routes = this.#getControllerMetadata<Record<string, GirouetteRoute>>(
      REFLECT_ROUTES_KEY,
      controller.controller.default
    )
    if (!routes) return

    for (const methodName in routes) {
      this.#collectSingleRoute(controller, methodName, routes[methodName])
    }
  }

  /**
   * Collects a single route definition
   */
  #collectSingleRoute(controller: ControllerToProcess, methodName: string, route: GirouetteRoute) {
    const group = this.#getControllerMetadata<GroupMetadata>(
      REFLECT_GROUP_KEY,
      controller.controller.default
    )
    const groupMiddleware = this.#getControllerMetadata<
      OneOrMore<MiddlewareFn | ParsedNamedMiddleware>
    >(REFLECT_GROUP_MIDDLEWARE_KEY, controller.controller.default)
    const groupDomain = this.#getControllerMetadata<string>(
      REFLECT_GROUP_DOMAIN_KEY,
      controller.controller.default
    )

    const finalRoute = this.#applyGroupConfiguration(route, methodName, group, groupMiddleware)

    // Get or create controller variable
    const controllerVar = this.#getControllerVar(controller.importUrl)

    // Build route line
    let routeLine = `router.route('${finalRoute.pattern}', ['${finalRoute.method}'], [${controllerVar}, '${methodName}'])`

    // Add route name
    if (finalRoute.name) {
      routeLine += `.as('${finalRoute.name}')`
    }

    // Add where clauses
    if (finalRoute.where?.length) {
      for (const { key, matcher } of finalRoute.where) {
        const matcherStr = matcher instanceof RegExp ? matcher.toString() : `'${matcher}'`
        routeLine += `.where('${key}', ${matcherStr})`
      }
    }

    // Add middleware
    if (finalRoute.middleware?.length) {
      for (const m of finalRoute.middleware) {
        const middlewareStr = this.#serializeMiddleware(m)
        routeLine += `.use(${middlewareStr})`
      }
    }

    // Add domain
    if (groupDomain) {
      routeLine += `.domain('${groupDomain}')`
    }

    this.#routeLines.push(routeLine)
  }

  /**
   * Collects resource routes from a controller
   */
  #collectResourceRoutes(controller: ControllerToProcess) {
    const resourceName = this.#getControllerMetadata<string>(
      REFLECT_RESOURCE_NAME_KEY,
      controller.controller.default
    )
    if (!resourceName) return

    try {
      const controllerVar = this.#getControllerVar(controller.importUrl)

      let resourceLine = `router.resource('${resourceName}', ${controllerVar})`

      // Add params
      const resourceParams = this.#getControllerMetadata<Record<string, string>>(
        REFLECT_RESOURCE_PARAMS_KEY,
        controller.controller.default
      )
      if (resourceParams) {
        resourceLine += `.params(${JSON.stringify(resourceParams)})`
      }

      // Add apiOnly
      const apiOnly = this.#getControllerMetadata<boolean>(
        REFLECT_RESOURCE_API_ONLY_KEY,
        controller.controller.default
      )
      if (apiOnly) {
        resourceLine += `.apiOnly()`
      }

      // Add only
      const only = this.#getControllerMetadata<ResourceActionNames[]>(
        REFLECT_RESOURCE_ONLY_KEY,
        controller.controller.default
      )
      if (only) {
        resourceLine += `.only(${JSON.stringify(only)})`
      }

      // Add except
      const except = this.#getControllerMetadata<ResourceActionNames[]>(
        REFLECT_RESOURCE_EXCEPT_KEY,
        controller.controller.default
      )
      if (except) {
        resourceLine += `.except(${JSON.stringify(except)})`
      }

      // Add middleware
      const resourceMiddleware = this.#getControllerMetadata<MiddlewareConfig[]>(
        REFLECT_RESOURCE_MIDDLEWARE_KEY,
        controller.controller.default
      )
      if (resourceMiddleware) {
        for (const { actions, middleware } of resourceMiddleware) {
          const middlewareStr = this.#serializeMiddleware(middleware)
          resourceLine += `.middleware(${JSON.stringify(actions)}, ${middlewareStr})`
        }
      }

      this.#routeLines.push(resourceLine)
    } catch (error) {
      this.#logger?.error({ error, resourceName }, '[Girouette] Error collecting resource routes')
    }
  }

  /**
   * Serializes middleware for code generation
   * Converts middleware to middleware.name() format
   */
  #serializeMiddleware(middleware: any): string {
    if (typeof middleware === 'string') {
      // Simple named middleware: 'auth' -> middleware.auth()
      return `middleware.${middleware}()`
    } else if (typeof middleware === 'object' && middleware !== null && middleware.name) {
      // ParsedNamedMiddleware: { name: 'auth', args: [...] } -> middleware.auth(...)
      const name = middleware.name
      if (middleware.args && middleware.args.length > 0) {
        // Has arguments: middleware.auth(arg1, arg2)
        const args = middleware.args.map((arg: any) => JSON.stringify(arg)).join(', ')
        return `middleware.${name}(${args})`
      }
      // No arguments: middleware.auth()
      return `middleware.${name}()`
    } else if (typeof middleware === 'function') {
      // Inline function middleware - keep as is
      return middleware.toString()
    }
    return String(middleware)
  }

  /**
   * Gets the controller reference in the controllers object
   * Example: #app/identity/controllers/auth_controller -> controllers.identity.Auth
   */
  #getControllerVar(importUrl: URL): string {
    const appRoot = this.app.appRoot.pathname
    let filePath = importUrl.pathname

    // Remove app root
    if (filePath.startsWith(appRoot)) {
      filePath = filePath.slice(appRoot.length)
      if (filePath.startsWith('/')) {
        filePath = filePath.slice(1)
      }
    }

    // Remove app/ prefix and .ts/.js extension
    filePath = filePath.replace(/^app\//, '').replace(/\.(ts|js)$/, '')

    // Parse the path: identity/controllers/auth_controller
    // -> feature: identity, controller: AuthController
    const parts = filePath.split('/')

    // For feature-based: identity/controllers/auth_controller
    // For traditional: controllers/posts_controller
    let feature = 'core'
    let controllerFile = ''

    if (parts.includes('controllers')) {
      const controllerIndex = parts.indexOf('controllers')
      if (controllerIndex > 0) {
        // Feature-based: identity/controllers/auth_controller
        feature = parts[controllerIndex - 1]
        controllerFile = parts[controllerIndex + 1]
      } else {
        // Traditional: controllers/posts_controller
        feature = 'core'
        controllerFile = parts[controllerIndex + 1]
      }
    }

    // Convert auth_controller -> Auth
    const controllerName = this.#toControllerClassName(controllerFile)

    return `controllers.${feature}.${controllerName}`
  }

  /**
   * Converts controller filename to class name
   * Example: auth_controller -> Auth, workload_items_controller -> WorkloadItems
   */
  #toControllerClassName(filename: string): string {
    // Remove _controller suffix
    const name = filename.replace(/_controller$/, '')

    // Convert snake_case to PascalCase
    return name
      .split('_')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join('')
  }

  /**
   * Applies group configuration to a route
   */
  #applyGroupConfiguration(
    route: GirouetteRoute,
    methodName: string,
    group?: GroupMetadata,
    groupMiddleware?: OneOrMore<MiddlewareFn | ParsedNamedMiddleware>
  ) {
    if (!group && !groupMiddleware) return route

    return {
      ...route,
      pattern: group?.prefix
        ? this.#prefixRoutePattern(route.pattern, group.prefix)
        : route.pattern,
      name: group?.name
        ? this.#prefixRouteName(route.name, group.name, methodName)
        : route.name || methodName,
      middleware: this.#mergeMiddleware(route.middleware, groupMiddleware),
    }
  }

  #prefixRoutePattern(pattern: string, prefix: string) {
    const cleanPrefix = prefix.startsWith('/') ? prefix : `/${prefix}`
    const cleanPattern = pattern.startsWith('/') ? pattern.slice(1) : pattern
    return `${cleanPrefix}/${cleanPattern}`
  }

  #prefixRouteName(name: string | undefined, prefix: string, methodName: string) {
    const routeName = name || methodName
    return routeName.startsWith(`${prefix}.`) ? routeName : `${prefix}.${routeName}`
  }

  #mergeMiddleware(
    routeMiddleware: OneOrMore<MiddlewareFn | ParsedNamedMiddleware>[],
    groupMiddleware?: OneOrMore<MiddlewareFn | ParsedNamedMiddleware>
  ) {
    if (!groupMiddleware) return [...(routeMiddleware || [])]

    const groupArray = Array.isArray(groupMiddleware) ? groupMiddleware : [groupMiddleware]
    return [...groupArray, ...(routeMiddleware || [])]
  }

  #getControllerMetadata<T>(key: string, controllerClass: FunctionConstructor): T | undefined {
    return Reflect.getMetadata(key, controllerClass)
  }
}
