import { join } from 'node:path'
import { readdir, writeFile, mkdir } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'

/**
 * Generates the start/routes.ts file from controllers
 */
export async function generateRoutesFile(appRoot: string, controllersPath: string = 'app') {
  console.log('[Girouette] Generating routes file...')
  console.log('[Girouette] App root:', appRoot)
  console.log('[Girouette] Controllers path:', controllersPath)

  const routeLines: string[] = []
  const fullControllersPath = join(appRoot, controllersPath)

  console.log('[Girouette] Full controllers path:', fullControllersPath)

  // Scan controllers and collect routes
  await scanDirectory(fullControllersPath, appRoot, routeLines)

  console.log('[Girouette] Found', routeLines.length, 'routes')

  // Generate the routes file
  const startDir = join(appRoot, 'start')
  const routesFilePath = join(startDir, 'routes.ts')

  await mkdir(startDir, { recursive: true })

  const fileContent = `/*
|--------------------------------------------------------------------------
| Routes file
|--------------------------------------------------------------------------
| Auto-generated by Girouette - DO NOT EDIT
|
| The routes file is used for defining the HTTP routes.
|
*/

import router from '@adonisjs/core/services/router'
import { middleware } from '#start/kernel'
import { controllers } from '#generated/controllers'

${routeLines.join('\n')}
`

  await writeFile(routesFilePath, fileContent, 'utf-8')
  console.log('[Girouette] Wrote routes to:', routesFilePath)
}

async function scanDirectory(directory: string, appRoot: string, routeLines: string[]) {
  console.log('[Girouette] Scanning directory:', directory)

  try {
    const files = await readdir(directory, { withFileTypes: true })
    console.log('[Girouette] Found', files.length, 'files/directories')

    for (const file of files) {
      const fullPath = join(directory, file.name)

      if (file.isDirectory()) {
        await scanDirectory(fullPath, appRoot, routeLines)
        continue
      }

      if (isControllerFile(file.name)) {
        console.log('[Girouette] Processing controller:', file.name)
        await processControllerFile(fullPath, appRoot, routeLines)
      }
    }
  } catch (error) {
    console.error('[Girouette] Error scanning directory:', directory, error)
  }
}

function isControllerFile(fileName: string): boolean {
  return fileName.endsWith('_controller.ts') || fileName.endsWith('_controller.js')
}

async function processControllerFile(filePath: string, appRoot: string, routeLines: string[]) {
  try {
    const path = pathToFileURL(filePath)
    const controller = await import(path.href)

    collectControllerRoutes(controller.default, path, appRoot, routeLines)
    collectResourceRoutes(controller.default, path, appRoot, routeLines)
  } catch (error) {
    console.error(`[Girouette] Error processing controller file: ${filePath}`, error)
  }
}

function collectControllerRoutes(
  controllerClass: any,
  importUrl: URL,
  appRoot: string,
  routeLines: string[]
) {
  const routes = Reflect.getMetadata('girouette:routes', controllerClass)
  if (!routes) return

  const controllerRef = getControllerReference(importUrl, appRoot)

  for (const methodName in routes) {
    const route = routes[methodName]
    let routeLine = `router.route('${route.pattern}', ['${route.method}'], [${controllerRef}, '${methodName}'])`

    if (route.name) {
      routeLine += `.as('${route.name}')`
    }

    if (route.where?.length) {
      for (const { key, matcher } of route.where) {
        const matcherStr = matcher instanceof RegExp ? matcher.toString() : `'${matcher}'`
        routeLine += `.where('${key}', ${matcherStr})`
      }
    }

    if (route.middleware?.length) {
      for (const m of route.middleware) {
        const middlewareStr = serializeMiddleware(m)
        routeLine += `.use(${middlewareStr})`
      }
    }

    if (route.domain) {
      routeLine += `.domain('${route.domain}')`
    }

    routeLines.push(routeLine)
  }
}

function collectResourceRoutes(
  controllerClass: any,
  importUrl: URL,
  appRoot: string,
  routeLines: string[]
) {
  const resourceName = Reflect.getMetadata('girouette:resource:name', controllerClass)
  if (!resourceName) return

  const controllerRef = getControllerReference(importUrl, appRoot)
  let resourceLine = `router.resource('${resourceName}', ${controllerRef})`

  const resourceParams = Reflect.getMetadata('girouette:resource:params', controllerClass)
  if (resourceParams) {
    resourceLine += `.params(${JSON.stringify(resourceParams)})`
  }

  const apiOnly = Reflect.getMetadata('girouette:resource:apiOnly', controllerClass)
  if (apiOnly) {
    resourceLine += `.apiOnly()`
  }

  const only = Reflect.getMetadata('girouette:resource:only', controllerClass)
  if (only) {
    resourceLine += `.only(${JSON.stringify(only)})`
  }

  const except = Reflect.getMetadata('girouette:resource:except', controllerClass)
  if (except) {
    resourceLine += `.except(${JSON.stringify(except)})`
  }

  const resourceMiddleware = Reflect.getMetadata('girouette:resource:middleware', controllerClass)
  if (resourceMiddleware) {
    for (const { actions, middleware: mw } of resourceMiddleware) {
      const middlewareStr = serializeMiddleware(mw)
      resourceLine += `.middleware(${JSON.stringify(actions)}, ${middlewareStr})`
    }
  }

  routeLines.push(resourceLine)
}

function getControllerReference(importUrl: URL, appRoot: string): string {
  let filePath = importUrl.pathname

  // Remove app root
  if (filePath.startsWith(appRoot)) {
    filePath = filePath.slice(appRoot.length)
    if (filePath.startsWith('/')) {
      filePath = filePath.slice(1)
    }
  }

  // Remove app/ prefix and .ts/.js extension
  filePath = filePath.replace(/^app\//, '').replace(/\.(ts|js)$/, '')

  // Parse the path
  const parts = filePath.split('/')

  let feature = 'core'
  let controllerFile = ''

  if (parts.includes('controllers')) {
    const controllerIndex = parts.indexOf('controllers')
    if (controllerIndex > 0) {
      feature = parts[controllerIndex - 1]
      controllerFile = parts[controllerIndex + 1]
    } else {
      feature = 'core'
      controllerFile = parts[controllerIndex + 1]
    }
  }

  const controllerName = toControllerClassName(controllerFile)
  return `controllers.${feature}.${controllerName}`
}

function toControllerClassName(filename: string): string {
  const name = filename.replace(/_controller$/, '')
  return name
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('')
}

function serializeMiddleware(middleware: any): string {
  if (typeof middleware === 'string') {
    return `middleware.${middleware}()`
  } else if (typeof middleware === 'object' && middleware !== null && middleware.name) {
    const name = middleware.name
    if (middleware.args && middleware.args.length > 0) {
      const args = middleware.args.map((arg: any) => JSON.stringify(arg)).join(', ')
      return `middleware.${name}(${args})`
    }
    return `middleware.${name}()`
  } else if (typeof middleware === 'function') {
    return middleware.toString()
  }
  return String(middleware)
}
